### ISSUE TITLE
使用mysql自动创建表未成功

### ISSUE THREAD

**Issue by linfini** [wildfirechat/server#101]
表不存在异常：
`java.sql.SQLSyntaxErrorException:` Table 'wfchat.t_sensitiveword' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1019)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
	at io.moquette.persistence.DatabaseStore.getSensitiveWord(DatabaseStore.java:2772)`

除此之外有个ssl连接警告信息。
flyway没有任何提示信息，不太明白哪里出了问题。本地wfchat数据有一张表，flyway_schema_history.

更新
wildfirechat_message.log
 [main] WARN  FileSystemScanner 53  - Skipping filesystem location:.\migrate\mysql (not found)

**Comment by linfini** [comment]
开发环境win10,不止这里找不到migrate路径下文件,debug时候也找不到hazelcast.xml路径(我修改 conf 配置项:hazelcast.conbfiguration broker/config/hazelcast.xml,配置 相对路径添加了borker);启动时也找不到wildfirechat.conf(我在启动参数里加了 -Dwildfirechat.path=broker 才可以).怎么感觉路径都找不到.

**Comment by heavyrain2012** [comment]
路径错误，编译打包后，使用release包进行运行验证，运行时注意在bin的上一级目录运行

**Comment by heavyrain2012** [comment]
超过一周未回复，问题关闭，如果还有问题请重新打开这个问题
