### ISSUE TITLE
Android视频通话无法弹出接通界面

### ISSUE THREAD

**Issue by droidsde** [wildfirechat/server#131]
错误日志
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.PowerManager$WakeLock.isHeld()' on a null object reference
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at cn.wildfirechat.avenginekit.g.onSensorChanged(Unknown Source:64)
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:862)
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:386)
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at android.os.Looper.loop(Looper.java:175)
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-12-05 22:32:46.701 30643-30643/com.droidsde.smart.hsr W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2019-12-05 22:32:46.702 30643-30643/com.droidsde.smart.hsr W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2019-12-05 22:32:46.704 30643-4006/com.droidsde.smart.hsr D/MediaPlayerNative: MediaPlayer::setVolume(1.000000, 1.000000)
2019-12-05 22:32:46.708 30643-4006/com.droidsde.smart.hsr I/MediaPlayerNative: setDataSource(112, 11008148, 71053)
2019-12-05 22:32:46.719 30643-31045/com.droidsde.smart.hsr W/System.err: android.app.PendingIntent$CanceledException
2019-12-05 22:32:46.719 30643-31045/com.droidsde.smart.hsr W/System.err:     at android.app.PendingIntent.send(PendingIntent.java:895)
2019-12-05 22:32:46.719 30643-31045/com.droidsde.smart.hsr W/System.err:     at android.app.PendingIntent.send(PendingIntent.java:707)
2019-12-05 22:32:46.719 30643-31045/com.droidsde.smart.hsr W/System.err:     at cn.wildfire.chat.kit.WfcUIKit.onCall(WfcUIKit.java:160)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at cn.wildfire.chat.kit.WfcUIKit.onReceiveCall(WfcUIKit.java:125)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at cn.wildfirechat.avenginekit.AVEngineKit.a(Unknown Source:153)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at cn.wildfirechat.avenginekit.AVEngineKit.lambda$aVPgOpqWuf8E9Ybxz8fo2n4D57k(Unknown Source:0)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at cn.wildfirechat.avenginekit.-$$Lambda$AVEngineKit$aVPgOpqWuf8E9Ybxz8fo2n4D57k.run(Unknown Source:4)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-12-05 22:32:46.720 30643-31045/com.droidsde.smart.hsr W/System.err:     at java.lang.Thread.run(Thread.java:784)

**Comment by heavyrain2012** [comment]
请给安卓项目提个issue，说明手机版本号，型号，和复现步骤，谢谢
