### ISSUE TITLE
发送不了图片

### ISSUE THREAD

**Issue by 704480904** [wildfirechat/server#152]
### OS version (e.g. `uname -a`)

服务器返回10090错误码 图片  语音文件  自带图片表情包 都发送不了，单聊发文字可以  我是 用你们编译的bat 运行的

**Comment by 704480904** [comment]
2020-01-08 11:14:04.414 3672-4362/? E/Watchdog: !@Sync 41140 [2020-01-08 11:14:04.414]
2020-01-08 11:14:04.987 21827-21827/cn.wildfirechat.chat:marsservice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.wildfirechat.chat:marsservice, PID: 21827
    java.lang.NullPointerException: Attempt to write to field 'cn.wildfirechat.message.Message cn.wildfirechat.model.ConversationInfo.lastMessage' on a null object reference
        at android.os.Parcel.readException(Parcel.java:1699)
        at android.os.Parcel.readException(Parcel.java:1646)
        at cn.wildfirechat.client.IOnReceiveMessageListener$Stub$Proxy.onRecall(IOnReceiveMessageListener.java:111)
        at cn.wildfirechat.client.ClientService.lambda$onRecallMessage$1$ClientService(ClientService.java:2089)
        at cn.wildfirechat.client.-$$Lambda$ClientService$yZ8tKhG_dxbjuETcCIyELRUyJr8.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by imndx** [comment]
> 2020-01-08 11:14:04.414 3672-4362/? E/Watchdog: !@sync 41140 [2020-01-08 11:14:04.414]
> 2020-01-08 11:14:04.987 21827-21827/cn.wildfirechat.chat:marsservice E/AndroidRuntime: FATAL EXCEPTION: main
> Process: cn.wildfirechat.chat:marsservice, PID: 21827
> java.lang.NullPointerException: Attempt to write to field 'cn.wildfirechat.message.Message cn.wildfirechat.model.ConversationInfo.lastMessage' on a null object reference
> at android.os.Parcel.readException(Parcel.java:1699)
> at android.os.Parcel.readException(Parcel.java:1646)
> at cn.wildfirechat.client.IOnReceiveMessageListener$Stub$Proxy.onRecall(IOnReceiveMessageListener.java:111)
> at cn.wildfirechat.client.ClientService.lambda$onRecallMessage$1$ClientService(ClientService.java:2089)
> at cn.wildfirechat.client.-$$Lambda$ClientService$yZ8tKhG_dxbjuETcCIyELRUyJr8.run(lambda)
> at android.os.Handler.handleCallback(Handler.java:751)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6682)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

这个是Android的问题，已经修复，请升级Android代码。
