### ISSUE TITLE
PC端扫码登录服务器报错，跟环境有关

### ISSUE THREAD

**Issue by totemtec** [wildfirechat/server#161]
### Actual behavior
Vultr上的机器就没事，七牛云就会报这个错误
服务器报错，PC端拿不到会话列表或者被踢下线

### Steps to reproduce
不知道怎么重现，对比了所有配置和文件

### Minimal yet complete reproducer code (or URL to code) or complete log file
详细wildfirechat.log见回复

### JVM version (e.g. `java -version`)
Java 1.8
### OS version (e.g. `uname -a`)
CentOS 7.7

**Comment by totemtec** [comment]
10/02/2020 22:08:59,155 [nioEventLoopGroup-5-3] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
10/02/2020 22:08:59,155 [pool-2-thread-1] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=ROUTE
10/02/2020 22:08:59,157 [pool-1-thread-3] INFO  DatabaseStore 1431  - Update rows 1
10/02/2020 22:08:59,421 [nioEventLoopGroup-5-4] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=GETTOKEN
10/02/2020 22:08:59,421 [pool-2-thread-2] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=GETTOKEN
10/02/2020 22:09:00,165 [nioEventLoopGroup-5-1] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=ROUTE
10/02/2020 22:09:00,166 [nioEventLoopGroup-5-1] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
10/02/2020 22:09:00,166 [pool-2-thread-4] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=ROUTE
10/02/2020 22:09:00,169 [pool-1-thread-1] INFO  DatabaseStore 1431  - Update rows 1
10/02/2020 22:09:02,265 [nioEventLoopGroup-5-2] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=ROUTE
10/02/2020 22:09:02,265 [pool-2-thread-3] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=ROUTE
10/02/2020 22:09:02,265 [nioEventLoopGroup-5-2] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
10/02/2020 22:09:02,267 [pool-1-thread-2] INFO  DatabaseStore 1431  - Update rows 1
10/02/2020 22:09:04,178 [epollEventLoopGroup-3-2] INFO  ProtocolProcessor 472  - Processing PUBLISH message. CId=6af37e3b9b7fbf411581001618935, topic=UPUI, messageId=46, qos=AT_LEAST_ONCE
10/02/2020 22:09:04,178 [epollEventLoopGroup-3-2] INFO  Qos1PublishHandler 152  - imHandler fromUser=xCxJxJvv, topic=UPUI
10/02/2020 22:09:04,178 [pool-2-thread-1] INFO  IMHandler 156  - imHandler fromUser=xCxJxJvv, clientId=6af37e3b9b7fbf411581001618935, topic=UPUI
10/02/2020 22:09:04,179 [pool-2-thread-1] INFO  ConnectionDescriptorStore 53  - Sending PUBACK message CId=<6af37e3b9b7fbf411581001618935>, messageId=46, errorCode=ERROR_CODE_SUCCESS



10/02/2020 22:11:28,328 [nioEventLoopGroup-5-1] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=ROUTE
10/02/2020 22:11:28,328 [nioEventLoopGroup-5-1] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
10/02/2020 22:11:28,328 [pool-2-thread-1] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=ROUTE
10/02/2020 22:11:28,331 [pool-1-thread-4] INFO  DatabaseStore 1431  - Update rows 1
10/02/2020 22:11:28,589 [nioEventLoopGroup-5-2] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=GETTOKEN
10/02/2020 22:11:28,590 [pool-2-thread-2] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=GETTOKEN
10/02/2020 22:11:29,307 [nioEventLoopGroup-5-3] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=ROUTE
10/02/2020 22:11:29,307 [pool-2-thread-4] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=ROUTE
10/02/2020 22:11:29,307 [nioEventLoopGroup-5-3] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
10/02/2020 22:11:29,310 [pool-1-thread-3] INFO  DatabaseStore 1431  - Update rows 1
10/02/2020 22:11:31,416 [nioEventLoopGroup-5-4] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=ROUTE
10/02/2020 22:11:31,416 [pool-2-thread-3] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=92115AB4-B6DC-4668-BA4D-ED55BCE11D77, topic=ROUTE
10/02/2020 22:11:31,416 [nioEventLoopGroup-5-4] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
10/02/2020 22:11:31,418 [pool-1-thread-1] INFO  DatabaseStore 1431  - Update rows 1
10/02/2020 22:11:37,720 [epollEventLoopGroup-3-1] INFO  ProtocolProcessor 472  - Processing PUBLISH message. CId=ac9b1f65fb5fecf91580972116084, topic=FP, messageId=28, qos=AT_LEAST_ONCE
10/02/2020 22:11:37,720 [epollEventLoopGroup-3-1] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=FP
10/02/2020 22:11:37,720 [pool-2-thread-1] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=ac9b1f65fb5fecf91580972116084, topic=FP
10/02/2020 22:11:37,722 [pool-2-thread-1] INFO  ConnectionDescriptorStore 53  - Sending PUBACK message CId=<ac9b1f65fb5fecf91580972116084>, messageId=28, errorCode=ERROR_CODE_SUCCESS
10/02/2020 22:11:38,668 [epollEventLoopGroup-3-3] ERROR NettyMQTTHandler 113  - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=4ac75ac290a987b01581341738064, cause=null, errorMessage=syscall:read(..) failed: Connection reset by peer
10/02/2020 22:11:38,668 [epollEventLoopGroup-3-3] ERROR NettyMQTTHandler 116  - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
10/02/2020 22:11:38,669 [epollEventLoopGroup-3-3] INFO  MessageMetricsHandler 72  - channel<DwEmDmDD> closing after read 7 messages and wrote 7 messages
10/02/2020 22:11:38,669 [epollEventLoopGroup-3-3] INFO  BytesMetricsHandler 73  - channel<DwEmDmDD> closing after read 315 bytes and wrote 0 bytes
10/02/2020 22:11:38,669 [epollEventLoopGroup-3-3] INFO  ProtocolProcessor 605  - Processing connection lost event. CId=4ac75ac290a987b01581341738064
10/02/2020 22:11:38,669 [epollEventLoopGroup-3-3] INFO  MessageMetricsHandler 72  - channel<DwEmDmDD> closing after read 7 messages and wrote 7 messages
10/02/2020 22:11:38,669 [pool-3-thread-1] INFO  HttpUtils 35  - POST to http://localhost:8888/user/online_event with data {"userId":"DwEmDmDD","clientId":"4ac75ac290a987b01581341738064","platform":2,"status":1,"timestamp":1581343898669}
10/02/2020 22:11:38,669 [epollEventLoopGroup-3-3] INFO  BytesMetricsHandler 73  - channel<DwEmDmDD> closing after read 315 bytes and wrote 0 bytes
10/02/2020 22:11:38,671 [OkHttp http://localhost:8888/...] INFO  HttpUtils 55  - POST to http://localhost:8888/user/online_event success with response: okhttp3.internal.http.RealResponseBody@45c7e5fe
10/02/2020 22:11:39,512 [epollEventLoopGroup-3-1] INFO  ProtocolProcessor 472  - Processing PUBLISH message. CId=ac9b1f65fb5fecf91580972116084, topic=FP, messageId=29, qos=AT_LEAST_ONCE
10/02/2020 22:11:39,512 [epollEventLoopGroup-3-1] INFO  Qos1PublishHandler 152  - imHandler fromUser=LTLuLukk, topic=FP
10/02/2020 22:11:39,512 [pool-2-thread-2] INFO  IMHandler 156  - imHandler fromUser=LTLuLukk, clientId=ac9b1f65fb5fecf91580972116084, topic=FP
10/02/2020 22:11:39,514 [pool-2-thread-2] INFO  ConnectionDescriptorStore 53  - Sending PUBACK message CId=<ac9b1f65fb5fecf91580972116084>, messageId=29, errorCode=ERROR_CODE_SUCCESS

**Comment by heavyrain2012** [comment]
pc sdk是需要授权的，请问sdk是正式购买的还是试用的，可以微信添加与你的联系人解决这个问题

**Comment by totemtec** [comment]
试用的，服务器80端口访问不了，我再看看

**Comment by heavyrain2012** [comment]
http://docs.wildfirechat.cn/faq/pc.html  你可以找到pc的日志微信发给我们
