### ISSUE TITLE
android端发送大的图片比如6M的图片就会导致连接断开，无法接受消息，特别是拍照发图片，现在手机像素高

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/server#163]
比如A给B拍照发图片，会导致B无法发送消息，也就是链接断开，需要重启消息服务才行
图片使用的是7niu的cdn

**Comment by dotcool** [comment]
服务器提示错误:
21/02/2020 16:39:59,358 [nioEventLoopGroup-5-1] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by heavyrain2012** [comment]
上传图片是客户端进行的，不经过服务器，请提供客户端的日志，如果有条件的话请提供客户端上传时的pcap包

**Comment by heavyrain2012** [comment]
问题长时间未回复，issue先关闭，如果有新情况需要补充，请重新打开issue或者重新提一个。
