### ISSUE TITLE
部分字段长度过长，在utf8mb4数据库中无法建立索引。如果有些字段不需要那么长，是否可以减小一点？

### ISSUE THREAD

**Issue by bigbencat** [wildfirechat/server#170]
### ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

SQL State  : 42000
Error Code : 1071
Message    : Specified key was too long; max key length is 767 bytes
Location   : ./migrate/mysql/V22__add_user_session_token_index.sql (/Users/groundlee/Documents/work/xbdedu/wildfire/server/distribution-0.38-bundle-tar/./migrate/mysql/V22__add_user_session_token_index.sql)
Line       : 1
Statement  : alter table `t_user_session` ADD INDEX `session_token_index` ( `_token` )

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
        at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:284)
        at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:281)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:164)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:161)
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:147)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:155)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:161)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:139)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1395)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
        at win.liyufan.im.DBUtil.init(DBUtil.java:103)
        at io.moquette.server.Server.startServer(Server.java:223)
        at io.moquette.server.Server.startServer(Server.java:215)
        at io.moquette.server.Server.startServer(Server.java:199)
        at io.moquette.server.Server.start(Server.java:109)

**Comment by imndx** [comment]
请参考这问题，[索引字段太长](http://bbs.wildfirechat.cn/thread-164.htm)

**Comment by zuoliang0** [comment]
文档看不到了，能在这里提供一下解决方案吗
