### ISSUE TITLE
群组无法删除

### ISSUE THREAD

**Issue by vfeng1221** [wildfirechat/server#195]
通过sdk调用解散群组接口，返回code=4,msg="server error"

im服务报错：
java.lang.NullPointerException
        at cn.wildfirechat.proto.WFCMessage$Message$Builder.setFromUser(WFCMessage.java:21590)
        at io.moquette.imhandler.GroupHandler.sendGroupNotification(GroupHandler.java:32)
        at io.moquette.imhandler.DismissGroupHandler.action(DismissGroupHandler.java:37)
        at io.moquette.imhandler.DismissGroupHandler.action(DismissGroupHandler.java:20)
        at io.moquette.imhandler.IMHandler.lambda$doHandler$0(IMHandler.java:191)
        at cn.wildfirechat.server.ThreadPoolExecutorWrapper.lambda$execute$0(ThreadPoolExecutorWrapper.java:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by heavyrain2012** [comment]
接口有个参数 是operator，请不用用null

**Comment by vfeng1221** [comment]
这个文档中写的是传操作者的id，是不是不限于管理员id，任何群成员id都可以？

**Comment by heavyrain2012** [comment]
对，任何id都可以
