### ISSUE TITLE
ios新建频道提交后 后台报错

### ISSUE THREAD

**Issue by hlwskgypmb** [wildfirechat/server#2]
### OS version (e.g. `uname -a`)
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column '_automatic' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1116)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1066)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1396)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1051)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:462)
	at io.moquette.persistence.DatabaseStore.lambda$updateChannelInfo$19(DatabaseStore.java:2073)
	at cn.wildfirechat.server.ThreadPoolExecutorWrapper.lambda$execute$0(ThreadPoolExecutorWrapper.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hlwskgypmb** [comment]
![1](https://user-images.githubusercontent.com/18130329/56565816-d0687900-65e3-11e9-82b6-519bf02eabf3.png)
![2](https://user-images.githubusercontent.com/18130329/56565817-d0687900-65e3-11e9-8bbc-08917ec0a4b1.png)
是数据表字段类型错误

**Comment by heavyrain2012** [comment]
协议栈没有对这个变量正确赋值，已经解决，点[这里](https://github.com/wildfirechat/proto/commit/e6fb540043fb6528db48113a8f8345152cd7b6fb)查看详情。
协议栈已经更新到android和iOS工程中，可以直接使用android或iOS工程

**Comment by hlwskgypmb** [comment]
好的，了解了 谢谢
