### ISSUE TITLE
服务端初次运行报错 FlywayException: Validate failed: Detected failed migration to version 31 (add user messages line)

### ISSUE THREAD

**Issue by Idolphint** [wildfirechat/server#202]
### Expected behavior
尝试运行了几次`sh ./bin/wildfirechat.sh`  但是都没有成功。报错内容是：
Total time for which application threads were stopped: 0.0107216 seconds, Stopping threads took: 0.0034796 seconds
Exception in thread "main" org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 31 (add user messages line)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at win.liyufan.im.DBUtil.init(DBUtil.java:101)
	at io.moquette.server.Server.startServer(Server.java:227)
	at io.moquette.server.Server.startServer(Server.java:219)
	at io.moquette.server.Server.startServer(Server.java:203)
	at io.moquette.server.Server.start(Server.java:113)
	at cn.wildfirechat.server.Server.main(Server.java:15)
Heap
 garbage-first heap   total 65536K, used 21504K [0x00000000f0800000, 0x00000000f0900200, 0x0000000100000000)
  region size 1024K, 14 young (14336K), 3 survivors (3072K)

### Steps to reproduce
已经按照说明，生成后修改数据库为本地数据库，本地数据库中查看flyway_schema_history表，发现在add user messages line            | SQL      | V31__add_user_messages_line.sql 处停了下来。是语法错误吗？

### JVM version (e.g. `java -version`)
1.8JDK
### OS version (e.g. `uname -a`)
Ubuntu16.04
mysql 5.7

**Comment by Idolphint** [comment]
这不是第一次运行sh 命令，目前数据库表中已经存在t_user_message0-127的表了。
印象里之前有一次报错是，line已存在云云。难道是V31....sql那个文件有重复内容？？但是检查了一下也没有重复的行。

**Comment by heavyrain2012** [comment]
请不要手动操作数据库，程序启动时会自动创建库和表。您可以试试把数据库drop掉，然后重新启动试试

**Comment by Idolphint** [comment]
已解决，是这样的！
