### ISSUE TITLE
我之前部署了一套服务端是可以正常使用，但是我复制了一份，放在其他服务器上运行就提示这个错误

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/server#240]
Total time for which application threads were stopped: 0.0236782 seconds, Stopping threads took: 0.0000344 seconds
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at io.moquette.persistence.MemoryMessagesStore.<init>(MemoryMessagesStore.java:184)
	at io.moquette.persistence.MemoryStorageService.<init>(MemoryStorageService.java:35)
	at io.moquette.server.Server.instantiateConfiguredStore(Server.java:292)
	at io.moquette.server.Server.initStore(Server.java:283)
	at io.moquette.server.Server.startServer(Server.java:256)
	at io.moquette.server.Server.startServer(Server.java:219)
	at io.moquette.server.Server.startServer(Server.java:203)
	at io.moquette.server.Server.start(Server.java:113)
	at cn.wildfirechat.server.Server.main(Server.java:15)
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at io.moquette.persistence.MemoryMessagesStore.<init>(MemoryMessagesStore.java:192)
	at io.moquette.persistence.MemoryStorageService.<init>(MemoryStorageService.java:35)
	at io.moquette.server.Server.instantiateConfiguredStore(Server.java:292)
	at io.moquette.server.Server.initStore(Server.java:283)
	at io.moquette.server.Server.startServer(Server.java:256)
	at io.moquette.server.Server.startServer(Server.java:219)
	at io.moquette.server.Server.startServer(Server.java:203)
	at io.moquette.server.Server.start(Server.java:113)
	at cn.wildfirechat.server.Server.main(Server.java:15)
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at io.moquette.persistence.MemoryMessagesStore.<init>(MemoryMessagesStore.java:200)
	at io.moquette.persistence.MemoryStorageService.<init>(MemoryStorageService.java:35)
	at io.moquette.server.Server.instantiateConfiguredStore(Server.java:292)
	at io.moquette.server.Server.initStore(Server.java:283)
	at io.moquette.server.Server.startServer(Server.java:256)
	at io.moquette.server.Server.startServer(Server.java:219)
	at io.moquette.server.Server.startServer(Server.java:203)
	at io.moquette.server.Server.start(Server.java:113)
	at cn.wildfirechat.server.Server.main(Server.java:15)

数据库一致，启动路劲一致

**Comment by heavyrain2012** [comment]
应该是配置项缺失导致的，是不是升级版本时没有更新配置文件？更新对应的配置文件应该就没有问题了

**Comment by dotcool** [comment]
哦哦，好的。我看看
