### ISSUE TITLE
升级后无法正常运行

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#358]
从0.49->0.60 

升级完毕出现以下问题，检查了好几遍配置文件也没有发现问题

 [Times: user=0.01 sys=0.01, real=0.01 secs] 
Total time for which application threads were stopped: 0.0095312 seconds, Stopping threads took: 0.0000445 seconds
Exception in thread "main" org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration version 17
-> Applied to database : 102176056
-> Resolved locally    : 0
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at win.liyufan.im.DBUtil.init(DBUtil.java:108)
	at io.moquette.server.Server.startServer(Server.java:228)
	at io.moquette.server.Server.startServer(Server.java:220)
	at io.moquette.server.Server.startServer(Server.java:204)
	at io.moquette.server.Server.start(Server.java:114)

**Comment by mankind-evolve** [comment]
执行修复数据库代码后成功
