### ISSUE TITLE
wildfirechat.conf 里面，没有配置mysql连接相关信息

### ISSUE THREAD

**Issue by chris-quant1216** [wildfirechat/server#366]
embed.db 0   设置使用mysql，但找不到任何配置连接信息的地方，启动后报如下错误。
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at win.liyufan.im.DBUtil.init(DBUtil.java:93)
	at io.moquette.server.Server.startServer(Server.java:227)
	at io.moquette.server.Server.startServer(Server.java:219)
	at io.moquette.server.Server.startServer(Server.java:203)
	at io.moquette.server.Server.start(Server.java:113)
	at cn.wildfirechat.server.Server.main(Server.java:15)

**Comment by chris-quant1216** [comment]
已自行解决。
