### ISSUE TITLE
在运行大量 ServerApi 请求一阵时间后 或者 自然运行1-2天后，Hazelcast会突然挂掉，导致应用无法正常运行

### ISSUE THREAD

**Issue by branchzero** [wildfirechat/server#377]
#### 操作说明

在运行大量ServerApi 请求一阵时间 或者 自然运行1-2天后，Hazelcast会突然挂掉，导致应用无法正常运行

#### 表现现象

所有涉及到的业务请求全部挂掉，包含但不限于好友列表、会话列表等

#### 预期结果

能够正常运行

#### 补充条件

偶发性

#### demo对比结果

无

#### 发生问题这段时间前后的日志

```
25/05/2021 21:51:38,909 [OkHttp http://api-web:8000/...] INFO  HttpUtils 68  - POST to http://api-web:8000/callback/event/user_online success with response: okhttp3.internal.http.RealResponseBody@4276ccc1
25/05/2021 21:51:45,079 [nioEventLoopGroup-5-48] INFO  Qos1PublishHandler 150  - imHandler fromUser=5dcb8600-4f8f-4002-a785-d97b4945920d, topic=UPUI
25/05/2021 21:51:45,079 [nioEventLoopGroup-5-50] INFO  Qos1PublishHandler 150  - imHandler fromUser=5dcb8600-4f8f-4002-a785-d97b4945920d, topic=UPUI
25/05/2021 21:51:45,474 [pool-2-thread-50] INFO  IMHandler 154  - imHandler fromUser=5dcb8600-4f8f-4002-a785-d97b4945920d, clientId=abe1f06de05c1be81621600002973, topic=UPUI
25/05/2021 21:51:45,474 [pool-2-thread-11] INFO  IMHandler 154  - imHandler fromUser=5dcb8600-4f8f-4002-a785-d97b4945920d, clientId=abe1f06de05c1be81621600002973, topic=UPUI
25/05/2021 21:51:51,015 [pool-5-thread-1] ERROR RequestInfo 38  - Request timeout. fromUser 5dcb8600-4f8f-4002-a785-d97b4945920d, cliendId abe1f06de05c1be81621600002973, requestId 165243, request UPUI
25/05/2021 21:51:56,028 [nioEventLoopGroup-5-52] INFO  Qos1PublishHandler 150  - imHandler fromUser=42bb146e-3ca0-426c-91d5-d7b9eb619ebd, topic=UPUI
25/05/2021 21:51:54,344 [epollEventLoopGroup-3-88] INFO  ProtocolProcessor 183  - Processing CONNECT message. CId=98f8df860bd7d7081621615222030, username=027aace7-7753-4f44-ae67-6c0935655950
25/05/2021 21:51:53,139 [epollEventLoopGroup-3-86] INFO  ProtocolProcessor 523  - Processing DISCONNECT message. CId=45c0367543b9329e1621615746914, clearSession=false
25/05/2021 21:52:08,620 [epollEventLoopGroup-3-86] INFO  ProtocolProcessor 608  - Removing will message. ClientId=45c0367543b9329e1621615746914
25/05/2021 21:51:52,141 [epollEventLoopGroup-3-87] INFO  ProtocolProcessor 183  - Processing CONNECT message. CId=040435ef3bf5f13e1621747459451, username=298fa101-5b33-4e75-9faa-415d4e71d85a
25/05/2021 21:51:51,015 [pool-5-thread-2] ERROR RequestInfo 38  - Request timeout. fromUser 5dcb8600-4f8f-4002-a785-d97b4945920d, cliendId abe1f06de05c1be81621600002973, requestId 165244, request UPUI
25/05/2021 21:52:15,939 [epollEventLoopGroup-3-86] INFO  ConnectionDescriptor 83  - Closing connection descriptor. MqttClientId = 45c0367543b9329e1621615746914.
25/05/2021 21:52:15,938 [epollEventLoopGroup-3-71] ERROR NettyMQTTHandler 113  - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=e44b664c691dbc881621695068877, cause=null, errorMessage=syscall:read(..) failed: Connection reset by peer
25/05/2021 21:52:15,594 [epollEventLoopGroup-3-91] INFO  ProtocolProcessor 183  - Processing CONNECT message. CId=b5ecfd647d1f3e2b1621608351069, username=c6700b0b-ca25-4da6-8e03-16d3520d16b4
25/05/2021 21:52:14,474 [epollEventLoopGroup-3-92] INFO  ProtocolProcessor 183  - Processing CONNECT message. CId=45c0367543b9329e1621615746914, username=2faa7275-e365-41a7-89d5-bd8f6e41d83b
25/05/2021 21:52:09,722 [epollEventLoopGroup-3-67] ERROR NettyMQTTHandler 113  - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=99fa582c8b8a37211621676558526, cause=null, errorMessage=syscall:read(..) failed: Connection reset by peer
25/05/2021 21:52:04,383 [epollEventLoopGroup-3-90] INFO  MoquetteIdleTimeoutHandler 37  - Firing channel inactive event. MqttClientId = 6b4a4cb826e08fa41621913022054.
25/05/2021 21:52:03,985 [epollEventLoopGroup-3-88] ERROR NettyMQTTHandler 93  - Exception was caught while processing MQTT message, null
com.hazelcast.core.HazelcastInstanceNotActiveException: HazelcastInstance[[172.21.0.3]:5701] is not active!
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getService(ProxyRegistry.java:73)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.<init>(ProxyRegistry.java:55)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:81)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:79)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:107)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getOrCreateRegistry(ProxyServiceImpl.java:138)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:146)
	at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:379)
	at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:179)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:98)
	at io.moquette.persistence.MemoryMessagesStore.getUserStatus(MemoryMessagesStore.java:2158)
	at io.moquette.spi.impl.ProtocolProcessor.login(ProtocolProcessor.java:301)
	at io.moquette.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:205)
	at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:54)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:55)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.base/java.lang.Thread.run(Unknown Source)
25/05/2021 21:52:02,113 [pool-5-thread-1] ERROR RequestInfo 38  - Request timeout. fromUser 42bb146e-3ca0-426c-91d5-d7b9eb619ebd, cliendId a05a186386978d751621854931890, requestId 165245, request UPUI
25/05/2021 21:52:02,113 [nioEventLoopGroup-5-54] INFO  Qos1PublishHandler 150  - imHandler fromUser=notification, topic=MS
25/05/2021 21:51:59,522 [pool-2-thread-83] INFO  IMHandler 154  - imHandler fromUser=42bb146e-3ca0-426c-91d5-d7b9eb619ebd, clientId=a05a186386978d751621854931890, topic=UPUI
25/05/2021 21:51:57,951 [nioEventLoopGroup-5-53] INFO  Qos1PublishHandler 150  - imHandler fromUser=42bb146e-3ca0-426c-91d5-d7b9eb619ebd, topic=UPUI
25/05/2021 21:51:56,378 [epollEventLoopGroup-3-89] INFO  ProtocolProcessor 183  - Processing CONNECT message. CId=b5ecfd647d1f3e2b1621608351069, username=c6700b0b-ca25-4da6-8e03-16d3520d16b4
25/05/2021 21:52:31,911 [pool-2-thread-61] INFO  IMHandler 154  - imHandler fromUser=42bb146e-3ca0-426c-91d5-d7b9eb619ebd, clientId=a05a186386978d751621854931890, topic=UPUI
25/05/2021 21:52:31,911 [pool-2-thread-1] INFO  IMHandler 154  - imHandler fromUser=notification, clientId=null, topic=MS
25/05/2021 21:52:31,910 [epollEventLoopGroup-3-88] WARN  DefaultChannelPipeline 151  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
com.hazelcast.core.HazelcastInstanceNotActiveException: HazelcastInstance[[172.21.0.3]:5701] is not active!
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getService(ProxyRegistry.java:73)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.<init>(ProxyRegistry.java:55)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:81)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:79)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:107)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getOrCreateRegistry(ProxyServiceImpl.java:138)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:146)
	at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:379)
	at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:179)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:98)
	at io.moquette.persistence.MemoryMessagesStore.getUserStatus(MemoryMessagesStore.java:2158)
	at io.moquette.spi.impl.ProtocolProcessor.login(ProtocolProcessor.java:301)
	at io.moquette.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:205)
	at io.moquette.server.netty.NettyMQTTHandler.channelRead(NettyMQTTHandler.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:54)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:55)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### 补充说明

发生问题是在清晨，正常应该没多少业务量，跑IM的机器是64C128G配置，目前IM上共有60W用户，日消息量3-4W的样子，发生问题是在清晨，属于业务低峰期，应该没有太多压力。
环境是运行在docker里面的，想知道如何才能知道相关业务运作是否正常，是否存在这样一个server-api来方便做healthcheck，以便在检测不正常后自动重启应用。

**Comment by heavyrain2012** [comment]
从网上查了一下，一般都是资源不够用造成的，可以查一下，给IM服务分配了多少内存，可以多分一点。另外可以考虑更换为专业版IM服务，专业版效率更高，能减少硬件资源的消耗

**Comment by branchzero** [comment]
好像JVM_XMX和JVM_XMS我注入到容器里面的时候给的很小，已经调整了，我先观察下情况，多谢：）
