### ISSUE TITLE
服务端错误

### ISSUE THREAD

**Issue by MyAllures** [wildfirechat/server#390]
2021-07-14 12:05:05,216 ERROR [epollEventLoopGroup-3-3] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=4b50eed5083c12821625996385531, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 12:05:05,218 ERROR [epollEventLoopGroup-3-3] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 12:59:16,600 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=4b50eed5083c12821625996385531, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 12:59:16,600 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 13:27:33,841 ERROR [epollEventLoopGroup-3-2] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=12b9928c03759dcc1625928495985, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 13:27:33,841 ERROR [epollEventLoopGroup-3-2] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 13:27:44,459 ERROR [epollEventLoopGroup-3-3] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=12b9928c03759dcc1625928495985, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 13:27:44,459 ERROR [epollEventLoopGroup-3-3] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 13:31:25,869 ERROR [epollEventLoopGroup-3-4] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=12b9928c03759dcc1625928495985, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 13:31:25,869 ERROR [epollEventLoopGroup-3-4] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 13:54:53,052 ERROR [epollEventLoopGroup-3-6] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=12b9928c03759dcc1625928495985, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 13:54:53,053 ERROR [epollEventLoopGroup-3-6] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 13:55:03,877 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=12b9928c03759dcc1625928495985, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 13:55:03,877 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 14:12:21,301 ERROR [epollEventLoopGroup-3-1] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=4b50eed5083c12821625996385531, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 14:12:21,301 ERROR [epollEventLoopGroup-3-1] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 15:13:19,850 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=4b50eed5083c12821625996385531, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 15:13:19,850 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 15:35:53,402 ERROR [epollEventLoopGroup-3-4] persistence.h (MemorySessionStore.java:326) - Can't find the session for client <A𪛔>
2021-07-14 15:35:53,406 ERROR [epollEventLoopGroup-3-4] persistence.h (MemorySessionStore.java:549) - Session of (A𪛔, A𪛔) is not exist true or deleted
2021-07-14 15:35:53,407 ERROR [epollEventLoopGroup-3-4] impl.f (ProtocolProcessor.java:245) - The MQTT login failure. Username=A𪛔
2021-07-14 16:53:59,697 ERROR [pool-3-thread-1] impl.h (Qos1PublishHandler.java:328) - null
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client 3bfe900a-fa5e-46ff-ab92-959c8ebc10bb in cache io.moquette.server.a@1fbc85e4
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:323) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:304) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:217) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:244) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:230) ~[netty-utility-4.1.12.Final.jar:?]
	at cn.wildfirechat.server.b.a(ThreadPoolExecutorWrapper.java:37) ~[netty-utility-4.1.12.Final.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2021-07-14 16:53:59,710 ERROR [pool-3-thread-2] impl.h (Qos1PublishHandler.java:328) - null
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client 3bfe900a-fa5e-46ff-ab92-959c8ebc10bb in cache io.moquette.server.a@1fbc85e4
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:323) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:304) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:217) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:244) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:230) ~[netty-utility-4.1.12.Final.jar:?]
	at cn.wildfirechat.server.b.a(ThreadPoolExecutorWrapper.java:37) ~[netty-utility-4.1.12.Final.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2021-07-14 16:53:59,719 ERROR [pool-3-thread-6] impl.h (Qos1PublishHandler.java:328) - null
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client 3bfe900a-fa5e-46ff-ab92-959c8ebc10bb in cache io.moquette.server.a@1fbc85e4
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:323) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:304) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:217) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:244) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:230) ~[netty-utility-4.1.12.Final.jar:?]
	at cn.wildfirechat.server.b.a(ThreadPoolExecutorWrapper.java:37) ~[netty-utility-4.1.12.Final.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2021-07-14 16:53:59,726 ERROR [pool-3-thread-4] impl.h (Qos1PublishHandler.java:328) - null
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client 3bfe900a-fa5e-46ff-ab92-959c8ebc10bb in cache io.moquette.server.a@1fbc85e4
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:323) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:304) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:217) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:244) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:230) ~[netty-utility-4.1.12.Final.jar:?]
	at cn.wildfirechat.server.b.a(ThreadPoolExecutorWrapper.java:37) ~[netty-utility-4.1.12.Final.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2021-07-14 16:53:59,728 ERROR [pool-3-thread-3] impl.h (Qos1PublishHandler.java:328) - null
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client 3bfe900a-fa5e-46ff-ab92-959c8ebc10bb in cache io.moquette.server.a@1fbc85e4
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:323) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:304) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.spi.impl.h.a(Qos1PublishHandler.java:217) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:244) ~[netty-utility-4.1.12.Final.jar:?]
	at io.moquette.imhandler.N.a(IMHandler.java:230) ~[netty-utility-4.1.12.Final.jar:?]
	at cn.wildfirechat.server.b.a(ThreadPoolExecutorWrapper.java:37) ~[netty-utility-4.1.12.Final.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2021-07-14 16:54:40,344 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=ab0d02cce42bb97c1626075633417, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 16:54:40,344 ERROR [epollEventLoopGroup-3-7] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 16:56:36,545 ERROR [pool-3-thread-5] persistence.h (MemorySessionStore.java:326) - Can't find the session for client <3bfe900a-fa5e-46ff-ab92-959c8ebc10bb>
2021-07-14 16:56:36,546 ERROR [pool-3-thread-5] persistence.h (MemorySessionStore.java:614) - Can't find the session for client <3bfe900a-fa5e-46ff-ab92-959c8ebc10bb>
2021-07-14 16:56:36,546 ERROR [epollEventLoopGroup-3-8] persistence.h (MemorySessionStore.java:326) - Can't find the session for client <3bfe900a-fa5e-46ff-ab92-959c8ebc10bb>
2021-07-14 16:59:24,425 ERROR [epollEventLoopGroup-3-3] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=fe87637f627fa16f1626253056447, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 16:59:24,425 ERROR [epollEventLoopGroup-3-3] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 16:59:40,466 ERROR [epollEventLoopGroup-3-2] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=ab0d02cce42bb97c1626075633417, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 16:59:40,466 ERROR [epollEventLoopGroup-3-2] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 17:00:16,101 ERROR [pool-3-thread-2] persistence.h (MemorySessionStore.java:549) - Session of (1cd355b6652a4f0e8e78c406a0717823, 3bfe900a-fa5e-46ff-ab92-959c8ebc10bb) is not exist true or deleted
2021-07-14 17:00:16,102 ERROR [pool-3-thread-4] persistence.h (MemorySessionStore.java:549) - Session of (1cd355b6652a4f0e8e78c406a0717823, 3bfe900a-fa5e-46ff-ab92-959c8ebc10bb) is not exist true or deleted
2021-07-14 17:04:11,310 ERROR [epollEventLoopGroup-3-5] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=6dc8aa9c60f1af9c1626252300889, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 17:04:11,310 ERROR [epollEventLoopGroup-3-5] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 17:09:42,869 ERROR [epollEventLoopGroup-3-4] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=fe87637f627fa16f1626253056447, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 17:09:42,869 ERROR [epollEventLoopGroup-3-4] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 17:11:23,468 ERROR [epollEventLoopGroup-3-1] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=82eda5e1-3571-45f4-bde5-17b12c7fcea7, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 17:11:23,468 ERROR [epollEventLoopGroup-3-1] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
2021-07-14 17:42:11,006 ERROR [epollEventLoopGroup-3-6] netty.h (NettyMQTTHandler.java:113) - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=fe87637f627fa16f1626253056447, cause=null, errorMessage=syscall:read(..) failed: 连接被对方重设
2021-07-14 17:42:11,006 ERROR [epollEventLoopGroup-3-6] netty.h (NettyMQTTHandler.java:116) - io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)

**Comment by heavyrain2012** [comment]
这种错误一般在手机后台被冻结或者杀掉会出现，是正常现象。请关注客户端是否使用正常

**Comment by heavyrain2012** [comment]
客户端有没有问题？
