### ISSUE TITLE
我刚拉下代码来，修改了在wildfirechat.conf中修改完ip,启动服务\server\broker\src\main\java\cn\wildfirechat\server\Server.java，中的main方法报错。我是想跑源码服务，不知道是不是起这里，求帮助

### ISSUE THREAD

**Issue by liulangzhexiaoke** [wildfirechat/server#419]
Exception in thread "main" java.lang.IllegalArgumentException: Can't locate file "null"
	at io.moquette.server.config.ResourceLoaderConfig.<init>(ResourceLoaderConfig.java:60)
	at io.moquette.server.config.ResourceLoaderConfig.<init>(ResourceLoaderConfig.java:36)
	at io.moquette.server.Server.defaultConfig(Server.java:159)
	at io.moquette.server.Server.start(Server.java:112)
	at cn.wildfirechat.server.Server.main(Server.java:15)

**Comment by heavyrain2012** [comment]
可以使用命令编译出软件包，然后再解压运行。我们不建议直接修改server的源码，可以通过server api调用IM服务
