### ISSUE TITLE
0.52升级0.54 出现数据库错误

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#433]
Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V45__add_user_messages_cont_type.sql failed
-----------------------------------------------------
SQL State  : 42S21
Error Code : 1060
Message    : Duplicate column name '_cont_type'
Location   : ./migrate/mysql/V45__add_user_messages_cont_type.sql (/www/im/imserver077/./migrate/mysql/V45__add_user_messages_cont_type.sql)
Line       : 1
Statement  : alter table `t_user_messages` add column `_cont_type` int(11) NOT NULL DEFAULT '0'

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:284)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:281)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:164)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:161)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:147)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:155)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:161)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:139)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1395)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at win.liyufan.im.DBUtil.init(DBUtil.java:120)
	at io.moquette.server.Server.startServer(Server.java:233)
	at io.moquette.server.Server.startServer(Server.java:225)
	at io.moquette.server.Server.startServer(Server.java:209)
	at io.moquette.server.Server.start(Server.java:119)
	at cn.wildfirechat.server.Server.main(Server.java:15)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V45__add_user_messages_cont_type.sql failed
-----------------------------------------------------
SQL State  : 42S21
Error Code : 1060
Message    : Duplicate column name '_cont_type'
Location   : ./migrate/mysql/V45__add_user_messages_cont_type.sql (/www/im/imserver077/./migrate/mysql/V45__add_user_messages_cont_type.sql)
Line       : 1
Statement  : alter table `t_user_messages` add column `_cont_type` int(11) NOT NULL DEFAULT '0'

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:253)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:202)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:125)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:77)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:367)
	... 23 more
Caused by: java.sql.SQLSyntaxErrorException: Duplicate column name '_cont_type'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:235)
	at org.flywaydb.core.internal.sqlscript.StandardSqlStatement.execute(StandardSqlStatement.java:42)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:189)
	... 26 more

**Comment by heavyrain2012** [comment]
看错误是t_user_messages表中添加新列 '_cont_type'出现重复的列，是不是你们自己修改过数据库的表结构

**Comment by mankind-evolve** [comment]
没有改过。

**Comment by mankind-evolve** [comment]
要是改的话，只修改过群组的name字段的长度

**Comment by heavyrain2012** [comment]
V45 之前的sql脚本没有在t_user_messages中新建_cont_type 列，怎么会出现列重复呢？你可以检查一直V45之前的sql脚本
