### ISSUE TITLE
0.52升0.79出现的错误  自动升级升不了，如何手动的去升级，是不是根据对应的sql语言升级数据库就行啊。 还需要其他的设置吗？ 怎么判断当前的版本是哪个版本

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/server#442]
Exception in thread "main" org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 45 (add user messages cont type)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at win.liyufan.im.DBUtil.init(DBUtil.java:120)
	at io.moquette.server.Server.startServer(Server.java:234)
	at io.moquette.server.Server.startServer(Server.java:226)
	at io.moquette.server.Server.startServer(Server.java:210)
	at io.moquette.server.Server.start(Server.java:120)
	at cn.wildfirechat.server.Server.main(Server.java:15)

**Comment by mankind-evolve** [comment]
我大体对比了两边的数据，好像是只改了排序的规则吧  如果把老数据库的数据直接导入一个新版本的空数据不知道可行不可行

**Comment by mankind-evolve** [comment]
我发现一个问题，虽然升级失败，但是应该加的字段都加上了。但是排序规则没有更新

**Comment by mankind-evolve** [comment]
t_user_messages表中已经添加列 '_cont_type'  怎么样跳过哪个出错的脚本呢？

**Comment by heavyrain2012** [comment]
把t_user_messages表中的'_cont_type删掉，然后检查一下t_user_messages_xxx表是否也有这一列，如果有的话也删掉。再删除 flyway_schema_history 表中的version 48哪一行，再重启IM服务就可以了

**Comment by mankind-evolve** [comment]
可行。已经顺利升级
