### ISSUE TITLE
服务器抛警告

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/server#468]
Server 抛出下面的异常，能帮忙看看什么原因吗？是否会对其他业务有影响？
```
2022-03-23 07:49:36,516 WARN  [nioEventLoopGroup-5-2] d.a (ActionHandler.java:73) - Connection reset by peer
2022-03-23 07:49:36,700 INFO  [nioEventLoopGroup-5-1] d.a (ActionHandler.java:37) - Http request whit url /
2022-03-23 07:49:36,700 ERROR [nioEventLoopGroup-5-1] a.e (FileAction.java:50) - Client [172.16.0.1] get file [/] failure!!!
2022-03-23 07:49:36,704 WARN  [nioEventLoopGroup-5-1] channel.DefaultChannelPipeline (DefaultChannelPipeline.java:1152) - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_252]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_252]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_252]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_252]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377) ~[?:1.8.0_252]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2022-03-23 07:49:36,704 WARN  [nioEventLoopGroup-5-1] d.a (ActionHandler.java:73) - Connection reset by peer
```
专业版Server版本信息：
```
{
	"tags":"null",
	"branch":"ddb364aa8b1921093dbf7724f22f08f5243d8949",
	"dirty":"null",
	"remoteOriginUrl":"git@github.com:heavyrain2012/server_commercial.git",
	"commitId":"ddb364aa8b1921093dbf7724f22f08f5243d8949",
	"commitIdAbbrev":"ddb364a",
	"describe":"moli-277-gddb364a",
	"describeShort":"null",
	"commitUserName":"heavyrain2012",
	"commitUserEmail":"heavyrain.lee@gmail.com",
	"commitMessageFull":"修改自己用户信息时，通知其他端\n",
	"commitMessageShort":"修改自己用户信息时，通知其他端",
	"commitTime":"20211209193840",
	"nodeIds":"1 ",
	"closestTagName":"null",
	"closestTagCommitCount":"null",
	"buildUserName":"imndx",
	"buildUserEmail":"imndxx@gmail.com",
	"buildTime":"20211210094252",
	"buildHost":"null",
	"buildVersion":"null",
	"verified":true,
	"currentNode":1,
	"runTime":14167
}
```

**Comment by heavyrain2012** [comment]
这个日志没有问题，一般手机放到后台被冻结就是这个日志
