### ISSUE TITLE
发送表情，图片失败

### ISSUE THREAD

**Issue by BarryYang1** [wildfirechat/server#500]
服务器报错如下
`java.lang.IndexOutOfBoundsException: writerIndex(1199) + minWritableBytes(1199) exceeds maxCapacity(1199): UnpooledSlicedByteBuf(ridx: 1199, widx: 1199, cap: 1199/1199, unwrapped: CompositeByteBuf(ridx: 0, widx: 1199, cap: 1199, components=2))
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:295)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1104)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1088)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:340)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
	at com.xiaoleilu.loServer.action.UploadFileAction.multipartUpload(UploadFileAction.java:116)
	at com.xiaoleilu.loServer.action.UploadFileAction.action(UploadFileAction.java:90)
	at com.xiaoleilu.loServer.action.Action.doAction(Action.java:123)
	at com.xiaoleilu.loServer.handler.ActionHandler.doAction(ActionHandler.java:138)
	at com.xiaoleilu.loServer.handler.ActionHandler.channelRead0(ActionHandler.java:48)
	at com.xiaoleilu.loServer.handler.ActionHandler.channelRead0(ActionHandler.java:27)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by heavyrain2012** [comment]
请提供更多的信息：
1，版本是多少？
2，你们有没有做修改？如果做修改了请用没有修改的版本验证一下？
3，错误的概率是多少？有什么特殊情况下才出吗？还是每次都出问题？

**Comment by BarryYang1** [comment]
1.版本:[创建群组时，检查群组类型的有效性](https://github.com/wildfirechat/imserver/commit/a394444c86d1739bb20c58982cfcb7598686ef9b)
在这个版本自行编译的
2.没有做修改
3.只要发表情/图片就报这个错误

**Comment by BarryYang1** [comment]
已解决，是改了netty版本的问题
