### ISSUE TITLE
server的18080端口服务没启动

### ISSUE THREAD

**Issue by pullwindyuan** [wildfirechat/server#52]
### OS version (win10)
部署完发布的0.24版本的server病成功运营后，再运行server项目中SDK下的main类进行测试的时候报错：
Create user user1 success
Create robot robot1 success
get user info success
get user info success
get user info success
get token success: AiIzSNC1/K5GnhCAbZgqbWrXn9IuNF+cvh8RyApDyHUY+nhgKhG+UNq4JciBI0lv8ESxS0Jn57IakcjbX0/wWRzvqY91Cih+B1xU24spZ76vRFeOM3T4K4faqrzC0YD7GCcNfGoneVzkcaUu9biO8RK6IeLU0E7UzXtPa2U3kTU=
block user done
check user status success
get block list done
block user done
check user status success
create group success
get group success
transfer success
get group member success
add group member success
kickoff group member success
send message success
recall message success
broad message success, send message to 1 users
http request content: http://localhost:18080/robot/message/send
java.lang.Exception: Http request error with code:404
	at cn.wildfirechat.sdk.utilities.RobotHttpUtils.httpJsonPost(RobotHttpUtils.java:75)
	at cn.wildfirechat.sdk.RobotService.sendMessage(RobotService.java:16)
	at cn.wildfirechat.sdk.Main.main(Main.java:308)
Exception in thread "main" java.lang.Exception: Http request error with code:404
	at cn.wildfirechat.sdk.utilities.RobotHttpUtils.httpJsonPost(RobotHttpUtils.java:75)
	at cn.wildfirechat.sdk.RobotService.sendMessage(RobotService.java:16)
	at cn.wildfirechat.sdk.Main.main(Main.java:308)

Process finished with exit code 1

**Comment by heavyrain2012** [comment]
你好，这个是test case写的有错误，我们最近版本已经修正，请验证，多谢！

**Comment by pullwindyuan** [comment]
好的，谢谢
