### ISSUE TITLE
im服务器部署时有问题

### ISSUE THREAD

**Issue by misunderstand5** [wildfirechat/server#591]
部署im服务器时有如下报错
警告：没有设置JVM内存参数！
请设置JVM参数Xmx和Xms，设置为您为IM服务预留的内存大小，注意需要刨除操作系统占用，如果有其它系统也需要相应去除占用。

数据库执行升级需要较长时间，可能长达数分钟或更长，请耐心等待，不要中断。。。
Exception in thread "main" org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 22 (add user session token index)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1482)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1364)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at win.liyufan.im.DBUtil.init(DBUtil.java:120)
	at io.moquette.server.Server.startServer(Server.java:234)
	at io.moquette.server.Server.startServer(Server.java:226)
	at io.moquette.server.Server.startServer(Server.java:210)
	at io.moquette.server.Server.start(Server.java:120)
	at cn.wildfirechat.server.Server.main(Server.java:15)

**Comment by heavyrain2012** [comment]
日志没有给全，你可以清除数据库后再运行一下把全部输出贴出来看看

**Comment by heavyrain2012** [comment]
有种可能是索引长度超长，你看看日志是不是有提示超长的信息，如果是索引长度超长可以网上查找一下解决办法，或者升级mysql版本也可以

**Comment by misunderstand5** [comment]
mysql8可以吗？

**Comment by heavyrain2012** [comment]
mysql8可以

**Comment by misunderstand5** [comment]
ok已解决，就是数据库版本的问题，我以前是5.6的谢谢

**Comment by misunderstand5** [comment]
open-web为平台的管理平台的管理页面；open-work
为客户端工作平台展示的页面。
要怎么使用

**Comment by imndx** [comment]
> open-web为平台的管理平台的管理页面；open-work 为客户端工作平台展示的页面。 要怎么使用

这个，请你单独到对应仓库提 issue，并详细描述具体的问题。
