### ISSUE TITLE
启动就报错 80 端口占用

### ISSUE THREAD

**Issue by kuchaguangjie** [wildfirechat/server#652]
> /mnt/star/git_repository/wildfirechat/wildfirechat
> openjdk version "1.8.0_382-382"
> OpenJDK Runtime Environment (build 1.8.0_382-382-b05)
> OpenJDK 64-Bit Server VM (build 25.382-b05, mixed mode)
> 警告：没有设置JVM内存参数！
> 请设置JVM参数Xmx和Xms，设置为您为IM服务预留的内存大小，注意需要刨除操作系统占用，如果有其它系统也需要相应去除占用。
> 
>             _  _      _   __  _                    _             _   
>  __      __(_)| |  __| | / _|(_) _ __  ___    ___ | |__    __ _ | |_ 
>  \ \ /\ / /| || | / _` || |_ | || '__|/ _ \  / __|| '_ \  / _` || __|
>   \ V  V / | || || (_| ||  _|| || |  |  __/ | (__ | | | || (_| || |_ 
>    \_/\_/  |_||_| \__,_||_|  |_||_|   \___|  \___||_| |_| \__,_| \__|
> 
> 您正在使用h2数据库，建议仅在开发验证或者用户数小于100人时才使用此数据库。正式上线时建议切换到MySQL数据库。
> java.net.SocketException: Permission denied
> 	at sun.nio.ch.Net.bind0(Native Method)
> 	at sun.nio.ch.Net.bind(Net.java:461)
> 	at sun.nio.ch.Net.bind(Net.java:453)
> 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
> 	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
> 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
> 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
> 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
> 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:750)
> 端口 80 已经被占用。请检查该端口被那个程序占用，找到程序停掉。
> 查找端口被那个程序占用的命令是: netstat -tunlp | grep 80
> 

但是 没有 占用, 多次 确认过了.

**Comment by kuchaguangjie** [comment]
需要 root 用户。
