### ISSUE TITLE
修改数据库名后启动报错，无法自动生成数据库表

### ISSUE THREAD

**Issue by zdmisif** [wildfirechat/server#8]
### 报错信息
Exception in thread "main" org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: Table 'abcde.test' doesn't exist
---------------------------------------------------------------------------
SQL State  : 42S02
Error Code : 1146
Message    : Table 'abcde.test' doesn't exist

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at win.liyufan.im.DBUtil.init(DBUtil.java:110)
	at io.moquette.server.Server.startServer(Server.java:218)
	at io.moquette.server.Server.startServer(Server.java:210)
	at io.moquette.server.Server.startServer(Server.java:194)
	at io.moquette.server.Server.start(Server.java:108)
	at cn.wildfirechat.server.Server.main(Server.java:15)
Caused by: java.sql.SQLSyntaxErrorException: Table 'abcde.test' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1019)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.initializeAutomaticTestTable(C3P0PooledConnectionPoolManager.java:1026)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.createPooledConnectionPool(C3P0PooledConnectionPoolManager.java:921)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:397)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager.getPool(C3P0PooledConnectionPoolManager.java:414)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	... 9 more

**Comment by zdmisif** [comment]
如果数据库里面已经自动生成过一个数据库，然后再修改数据库名，另外生成就会报错

**Comment by heavyrain2012** [comment]
最新代码已经修改，请检查
